.TH TRAFIX 1 "April 2025" "1.0.2" "User Commands"
.SH NAME
trafix \- Lightweight network monitoring tool for Linux
.SH SYNOPSIS
.B trafix
.SH DESCRIPTION
Trafix is a lightweight tool that provides real-time insights into connections, CPU, and network activity via a command-line interface.
.SH OPTIONS
.B -h, --help
Display this help message and exit.
.SH AUTHOR
Written by Masoud Bolhassani.
