

.\" SPDX-License-Identifier: GPL-3.0-or-later
.\" Copyright (C) 2025 Masoud Bolhassani.

.TH TRAFIX 1 "May 2026" "0.1.0" "User Commands"
.SH NAME
trafix \- Lightweight network monitoring tool for Linux
.SH SYNOPSIS
.B trafix
.RI [ OPTION ]
.SH DESCRIPTION
Trafix is a lightweight terminal user interface that provides real-time insights into Linux system, connection, and network activity.

Running
.B trafix
without options launches the interactive TUI.
.SH OPTIONS
.TP
.BR -h ", " --help
Display this help message and exit.
.TP
.BR -v ", " --version
Display version information and exit.
.SH AUTHOR
Written by Masoud Bolhassani.
